name: Update Cache

on:
  push:
    branches:
      - main
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  update-cache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: echo
        env:
          CI: true

      - name: Install dependencies
        run: npm ci
        env:
          CI: true
